### ISSUE TITLE
DefaultLayoutMergeStrategy NPE

### ISSUE THREAD

**Issue by davidhcarman** [structurizr/java#139]
I have been working in a workspace for about 2 weeks. I created a System Context, Container, Dynamic, and a Component Diagram in my workspace. All was good up to this point. Then I attempted to create a second Component Diagram. When I went to push my changes via the API, I got the below stack trace:

Dec 31, 2019 2:17:15 PM com.structurizr.api.StructurizrClient putWorkspace
SEVERE: java.lang.NullPointerException
Exception in thread "main" com.structurizr.api.StructurizrClientException: java.lang.NullPointerException
	at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:376)
	at com.openlending.structurizr.Step1.uploadWorkspaceToStructurizrStep1.java:168)
	at com.openlending.structurizr.Step1.main(Step1.java:161)
Caused by: java.lang.NullPointerException
	at com.structurizr.view.DefaultLayoutMergeStrategy.lambda$findElementView$0(DefaultLayoutMergeStrategy.java:71)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at com.structurizr.view.DefaultLayoutMergeStrategy.findElementView(DefaultLayoutMergeStrategy.java:71)
	at com.structurizr.view.DefaultLayoutMergeStrategy.copyLayoutInformation(DefaultLayoutMergeStrategy.java:35)
	at com.structurizr.view.View.copyLayoutInformationFrom(View.java:382)
	at com.structurizr.view.ViewSet.copyLayoutInformationFrom(ViewSet.java:638)
	at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:331)

I reverted my changes and attempted to push again with the same result. I reverted my workspace and attempted to push again (without the new Component View) and had the same error once again.

**Comment by beatw** [comment]
We are facing the same problem since some days...

**Comment by simonbrowndotje** [comment]
I've tried a few things, but I'm unable to reproduce this. Are you renaming anything (e.g. elements, views, etc) between runs of your client programs?

**Comment by simonbrowndotje** [comment]
v1.3.3 of the client library does address an issue with component views, although not the specific issue that you're facing. If you've not done so already, I'd recommend upgrading to the latest version, and seeing if that helps.

**Comment by davidhcarman** [comment]
@simonbrowndotje I was using the 1.3.2 client and 1.3.2 core. I upgraded both to 1.3.3 and I no longer have the issue. It seems the latest release fixed the issue, or possibly a change in the newer code broke the old client since I think I noticed this issue right around when it was released.
