### ISSUE TITLE
Unknown model item type on 'element'

### ISSUE THREAD

**Issue by kristofdepypere** [structurizr/java#298]
### Description

I'm having issues using the new Inspect feature.

We are getting a stacktrace running it from cli and in the onpremise webapp we even can make the instance crash. On one of our workspaces we are getting the following error:

```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at com.structurizr.cli.InspectCommand.findInspector(InspectCommand.java:134) [structurizr-cli.jar:]
	at com.structurizr.cli.InspectCommand.run(InspectCommand.java:83) [structurizr-cli.jar:]
	at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:83) [structurizr-cli.jar:]
	at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:104) [structurizr-cli.jar:]

Caused by: java.lang.IllegalArgumentException: Unknown model item type.
	at com.structurizr.view.Terminology.findTerminology(Terminology.java:139) ~[structurizr-core-2.1.1.jar:2.1.1]
	at com.structurizr.inspection.model.AbstractElementInspection.terminologyFor(AbstractElementInspection.java:23) ~[structurizr-inspection-2.1.1.jar:2.1.1]
	at com.structurizr.inspection.model.ElementNotIncludedInAnyViewsInspection.inspect(ElementNotIncludedInAnyViewsInspection.java:33) ~[structurizr-inspection-2.1.1.jar:2.1.1]
	at com.structurizr.inspection.model.AbstractElementInspection.run(AbstractElementInspection.java:17) ~[structurizr-inspection-2.1.1.jar:2.1.1]
	at com.structurizr.inspection.DefaultInspector.runModelInspections(DefaultInspector.java:74) ~[structurizr-inspection-2.1.1.jar:2.1.1]
	at com.structurizr.inspection.DefaultInspector.<init>(DefaultInspector.java:19) ~[structurizr-inspection-2.1.1.jar:2.1.1]
	... 7 more
```

After some trial and error I traced it back to the `element` keyword. validateWorkspace, validateWorkspaceDSL and rendering the workspace all works. There must be something missing in the inspect logic to handle `element`.

### Steps to reproduce

Hit Inspect on a workspace containing `element` in a `group`

### Severity

Critical

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
I can't reproduce this I'm afraid.

```
workspace {
    model {
        group "Group 1" {
            softwareSystem "A" {
                group "Group 2" {
                    container "B"
                }
            }
        }
    }
}
```

```
structurizr-cli % ./structurizr.sh inspect -w workspace.dsl 
ERROR  | workspace.scope                    | This workspace has no defined scope. It is recommended that the workspace scope is set to "Landscape" or "SoftwareSystem".
ERROR  | model.softwaresystem.description   | The software system "A" is missing a description.
ERROR  | model.softwaresystem.documentation | The software system "A" has containers, but is missing documentation.
ERROR  | model.softwaresystem.decisions     | The software system "A" has containers, but is missing decisions.
ERROR  | model.element.disconnected         | The software system "A" is disconnected - add a relationship to/from it, or consider removing it from the model.
ERROR  | model.element.noview               | The software system named "A" is not included on any views - add it to a view.
ERROR  | model.container.description        | The container "A.B" is missing a description.
ERROR  | model.container.technology         | The container "A.B" is missing a technology.
ERROR  | model.element.disconnected         | The container "A.B" is disconnected - add a relationship to/from it, or consider removing it from the model.
ERROR  | model.element.noview               | The container named "B" is not included on any views - add it to a view.
ERROR  | views.empty                        | This workspace has no views.
```

**Comment by simonbrowndotje** [comment]
Example to reproduce:

```
workspace {
    model {
        element "A"
    }
}
```
