### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by fcavaco** [structurizr/java#38]
Hi Simon,

I'm trying to updat a Structurizr workspace but failing for some reason. Just today was able to update.
WorkspaceID = 20371
I believe both key and secret are correct...

Exception I get:
Structurizr.Client.StructurizrClientException was unhandled
  HResult=-2146233088
  Message=There was an error putting the workspace: The remote server returned an error: (401) Unauthorized.
  Source=Structurizr.Core
  StackTrace:
       at Structurizr.Client.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
       at ConsoleApplication1.Program.Main(String[] args) in C:\Users\XXX\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 64
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233079
       Message=The remote server returned an error: (401) Unauthorized.
       Source=System
       StackTrace:
            at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
            at System.Net.WebClient.UploadString(Uri address, String method, String data)
            at System.Net.WebClient.UploadString(String address, String method, String data)
            at Structurizr.Client.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
       InnerException:

**Comment by simonbrowndotje** [comment]
Hi Francisco,

There was an issue raised on the .NET client recently where using UTF-8 characters would cause the "putWorkspace" operation to fail with an unauthorized message, which you can see more detail about here -> https://github.com/structurizr/dotnet/issues/3

Are you using the version of the .NET client from Nuget?

Cheers
Simon

**Comment by fcavaco** [comment]
yes, I am. 0.3.1

**Comment by fcavaco** [comment]
just found what character was causing the issue:

SoftwareSystem cdeSystem = model.AddSoftwareSystem(Location.Internal, "City Data Exchange (CDE)", "–");

"provides a service for the sale, purchase and sharing of a wide variety of data from multiple sources between all types of users in a city **–** businesses, city government, and citizens."
above does not work...

"provides a service for the sale, purchase and sharing of a wide variety of data from multiple sources between all types of users in a city **:** businesses, city government, and citizens."

this does work, by shifting from **–** to **:** 

not sure how this relates to a (401) Unauthorized.. its being defaulted for any exception I take?

**Comment by simonbrowndotje** [comment]
Thanks for letting me know. Yes, in summary, the presence of non-ASCII characters causes the MD5 digest to mismatch between client and server, which triggers the "unauthorized" response. I'll push out a new Nuget version that will fix this.
