### ISSUE TITLE
Exception NoClassDefFoundError for SourceCodeComponentFinderStrategy

### ISSUE THREAD

**Issue by jflalande** [structurizr/java#53]
Hi
I am trying to use a ComponentFinder based on a SourceCodeComponentFinderStrategy:
`ComponentFinder componentFinder = new ComponentFinder(
                forceCFI, "instru",
                new SourceCodeComponentFinderStrategy(new File(sourceRoot, "/src/"), 150));
componentFinder.findComponents();`

but I get the following exception:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/javadoc/Main
	at com.structurizr.analysis.SourceCodeComponentFinderStrategy.runJavaDoc(SourceCodeComponentFinderStrategy.java:118)
	at com.structurizr.analysis.SourceCodeComponentFinderStrategy.afterFindComponents(SourceCodeComponentFinderStrategy.java:62)
	at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:76)
	at Test.main(Test.java:102)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javadoc.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more`

I tried to google search about the fail of the loading of the class but did not find anything usefull. I tried also to replace the OpenJDK by the Sun JDK but the error is still there. Is this a bug or I missed something ?

**Comment by simonbrowndotje** [comment]
Assuming that you're not on Java 9 yet, I'm pretty sure you need the tools.jar file (JAVA_HOME/lib/tools.jar) on the classpath.

**Comment by jflalande** [comment]
That's it (Java 8) ! Solved :+1: 
Thank you...

**Comment by simonbrowndotje** [comment]
Thanks ... I've added a note to the documentation.
