### ISSUE TITLE
Structurizr could not find components in an application using spring boot 2.0.0.M7 

### ISSUE THREAD

**Issue by ghiama** [structurizr/java#67]
I am trying to document an application that uses spring boot version 2.0.0.M7. But The problem am having is that when i use "structurizr-spring" dependency to auto scan components it fails to locate them. I can see from my logs that when the component finder tries to find files that are specified (as packageToScan parameter) it goes through all the files existing in classpath including the jar file for the application. 

My project structure looks like this. I have application package and architecture package ( structurizr) gradle projects in the same level and in architecture's build.gradle i have added compile dependency to the application.

- app
   
- architecture

Here is code excerpt that shows how i am trying to find spring components

     ` ComponentFinder componentFinder = new ComponentFinder(
                webApplication, "com.mypackage.name",
                new SpringComponentFinderStrategy(
                        new ReferencedTypesSupportingTypesStrategy()
                )
        );

       componentFinder.findComponents();
     `

**Comment by engrun** [comment]
Can you provide the relevant logs? It will probably be valuable to the persons that can help with this issue

**Comment by simonbrowndotje** [comment]
If you output the workspace (using WorkspaceUtils. printWorkspaceAsJson), do you see the components in your model? Does your application have classes marked @Controller, etc?

**Comment by ghiama** [comment]
Hi again, Yes my application has Controllers and Services marked with @Controller and @Service annotations. Here is the output of workspace using WorkspaceUtils.printWorkspaceAsJson

`{
  "id" : 0,
  "name" : "Booking application",
  "description" : "Booking application",
  "model" : {
    "softwareSystems" : [ {
      "tags" : "Element,Software System",
      "id" : "1",
      "name" : "Api",
      "description" : "connects to external systems",
      "relationships" : [ {
        "tags" : "Relationship,Synchronous",
        "id" : "5",
        "sourceId" : "1",
        "destinationId" : "2",
        "description" : "Uses",
        "interactionStyle" : "Synchronous"
      } ],
      "location" : "Unspecified",
      "containers" : [ {
        "tags" : "Element,Container",
        "id" : "6",
        "name" : "BookingWebApplication",
        "description" : "forward booking data",
        "relationships" : [ {
          "tags" : "Relationship,Synchronous",
          "id" : "8",
          "sourceId" : "6",
          "destinationId" : "2",
          "description" : "POSTs to",
          "technology" : "HTTP1.1/JSON",
          "interactionStyle" : "Synchronous"
        } ],
        "technology" : "JAR"
      } ]
    }, {
      "tags" : "Element,Software System",
      "id" : "2",
      "name" : "External",
      "description" : "Weather external source",
      "location" : "Unspecified"
    }, {
      "tags" : "Element,Software System",
      "id" : "3",
      "name" : "Statistical Data Source",
      "description" : "statistics source",
      "relationships" : [ {
        "tags" : "Relationship,Synchronous",
        "id" : "4",
        "sourceId" : "3",
        "destinationId" : "1",
        "description" : "Uses",
        "interactionStyle" : "Synchronous"
      }, {
        "tags" : "Relationship,Synchronous",
        "id" : "7",
        "sourceId" : "3",
        "destinationId" : "6",
        "description" : "Uses",
        "technology" : "HTTP1.1/JSON",
        "interactionStyle" : "Synchronous"
      } ],
      "location" : "Unspecified"
    } ]
  },
  "documentation" : { },
  "views" : {
    "configuration" : {
      "branding" : { },
      "styles" : { }
    }
  }
}`

**Comment by engrun** [comment]
I have been debugging this project today. 
My findings:

* Gradle based build - 4.x
* Two modules

```
- root
 -- architecture
 -- api 
```

* "architecture" module has a project module dependency to api
```
compile project(:api)
```

When debugging the main method in the architecture module **from IntelliJ IDEA**: **it works**
, that is, the json contains the 4 relevant controllers.

When running from command line, using any version of Gradle 4.x : **it does not work**, that is, the json does not contain any components.
(I'm having trouble debugging from command line as org.gradle.debug=true does not halt the execution)

I tried to downgrade Gradle to 2.x/3.x as we have working examples using this combination, however, the Spring Boot gradle plugin requires 4.x, so that was not doable. 

Hope this helps

**Comment by simonbrowndotje** [comment]
This sounds like a problem with the dependencies, since it works from IntelliJ IDEA. It's likely that you don't need the compile time dependency from the ```architecture``` module to the ```api``` module. You do need a *runtime* dependency though. I would be tempted to output the classpath in your architecture program after it starts, and try doing a ```Class.forName(...)``` on a class that you know should exist in the ```api``` module.

**Comment by engrun** [comment]
Changing from compile scope to runtime does not fix the problem.

However, you are absolutely right, there must be a problem with the dependencies.
Both doing an explicit import and Class.forName() fails

1)
Explicit import fails with "package x.x.x.x does not exist"

2)
Class.forName() fails with "Exception in thread "main" java.lang.ClassNotFoundException:"

I will report this to the developers, so they can look into their dependency config.

**Comment by engrun** [comment]
hi
there is a "WARN" in the log, which gives us some interesting info.

It seems like the jar file we are depending on, is skipped. 


```
09:32:23.146 [main] WARN org.reflections.Reflections - could not create Dir using jarFile from url file:/Users/engrun/Development/git-repos/ncdx-mats-api/api/build/libs/api.jar. skipping.
java.lang.NullPointerException: null
        at java.util.zip.ZipFile.<init>(ZipFile.java:207)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:216)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:240)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at com.structurizr.analysis.DefaultTypeRepository.<init>(DefaultTypeRepository.java:53)
        at com.structurizr.analysis.AbstractComponentFinderStrategy.beforeFindComponents(AbstractComponentFinderStrategy.java:50)
        at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:68)
        at architecture.Architecture.createArchitecture(Architecture.java:63)
        at architecture.StructurizrMain.main(StructurizrMain.java:7)
09:32:23.149 [main] WARN org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: Could not open url connection
        at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:37)
        at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33)
        at org.reflections.Reflections.scan(Reflections.java:243)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at com.structurizr.analysis.DefaultTypeRepository.<init>(DefaultTypeRepository.java:53)
        at com.structurizr.analysis.AbstractComponentFinderStrategy.beforeFindComponents(AbstractComponentFinderStrategy.java:50)
        at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:68)
        at architecture.Architecture.createArchitecture(Architecture.java:63)
        at architecture.StructurizrMain.main(StructurizrMain.java:7)
Caused by: java.io.FileNotFoundException: /Users/engrun/Development/git-repos/ncdx-mats-api/api/build/libs/api.jar (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:36)
        ... 9 common frames omitted
09:32:23.208 [main] WARN org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/engrun/Development/git-repos/ncdx-mats-api/architecture/build/resources/main]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:240)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at com.structurizr.analysis.DefaultTypeRepository.<init>(DefaultTypeRepository.java:53)
        at com.structurizr.analysis.AbstractComponentFinderStrategy.beforeFindComponents(AbstractComponentFinderStrategy.java:50)
        at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:68)
        at architecture.Architecture.createArchitecture(Architecture.java:63)
        at architecture.StructurizrMain.main(StructurizrMain.java:7)
09:32:23.221 [main] INFO org.reflections.Reflections - Reflections took 157 ms to scan 122 urls, producing 0 keys and 0 values 

```

**Comment by engrun** [comment]
From the gradle log we can see
```
09:47:35.446 [main] DEBUG org.reflections.Reflections - going to scan these urls:
..
..
file:/Users/engrun/Development/git-repos/ncdx-mats-api/api/build/libs/api.jar
..
..
```

so the file from the dependent module is definitely being scanned

**Comment by simonbrowndotje** [comment]
Is the file being specified on the runtime classpath, but it doesn't exist? Since it's working via IDEA, this sounds like a Gradle configuration problem. Here's an example of how I've used the run task with Structurizr -> https://github.com/structurizr/api/blob/master/docs/build.gradle#L25 (this is a parent-child relationship, so not the same, but it shows the classpath being specified).

**Comment by engrun** [comment]
The file exist, we have checked that. When it doesn't, it will output a FileNotFoundException

**Comment by simonbrowndotje** [comment]
I'll happily take a closer look if you want to zip the folder and e-mail it to me...

**Comment by engrun** [comment]
Thanks, I'll will! Give me a couple of minutes to clear some password and secrets

**Comment by gilgamesjh** [comment]
I suspect the problem stems from the build task in the Spring Boot build plugin. This creates a non standard jar file, and Reflections is not able to read correctly from it. A solution is probably to add a task that can build a regular jar file, without the embedded jars and the Spring repackaging, and use that instead. Just a suspicion, though.

**Comment by simonbrowndotje** [comment]
Agreed ... or just point the runtime classpath to the build/classes/java/main folder instead?

**Comment by engrun** [comment]
```
runtime files('../api/build/classes/java/main')
```

fixes this problem
