### ISSUE TITLE
ComponentFinder crashes on inner classes

### ISSUE THREAD

**Issue by danieldistler** [structurizr/java#68]
All the `SupportingTypesStrategy` implementations in structurizr-core seem to use `Class::getCanonicalName` to convert `Class` objects to `String`s. Later these strings are converted back to classes via `ClassLoader::loadClass` in `TypeUtils.getVisibility`. Unfortunately this does not work for inner classes.
For the class `Inner` in class `Bar` in package `foo` e.g.
```
Class::getCanonicalName = foo.Bar.Inner
Class::getName = foo.Bar$Inner
```
and in `ClassLoader::loadClass` you must use `foo.Bar$Inner` to load the inner class. `foo.Bar.Inner` will lead to an exception like the one I see when running ComponentFinder on my project:
```
Exception in thread "main" java.lang.IllegalArgumentException: The specified type could not be found.
	at com.structurizr.analysis.TypeUtils.getVisibility(TypeUtils.java:33)
	at com.structurizr.analysis.AbstractComponentFinderStrategy.findSupportingTypes(AbstractComponentFinderStrategy.java:85)
	at com.structurizr.analysis.AbstractComponentFinderStrategy.afterFindComponents(AbstractComponentFinderStrategy.java:70)
	at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:76)
```

**Comment by danieldistler** [comment]
already solved with de629f88ac48ae08b6f9a0cf86a6fa7114947ab2
should have looked in the repo before opening a bug, sorry!
latest maven release (1.0.0-RC4) does not include the fix yet
