### ISSUE TITLE
After I have saved a model on structurizr and reading it with the client again, I get a Nullpointer Exception

### ISSUE THREAD

**Issue by klu2** [structurizr/java#7]
I had an existing model (workspace 111), saved it on structurizr and then fetched it again with the client. Then I got the following exception:

Exception in thread "main" com.structurizr.io.StructurizrReaderException: Could not read JSON
	at com.structurizr.io.json.JsonReader.read(JsonReader.java:23)
	at com.structurizr.api.StructurizrClient.getWorkspace(StructurizrClient.java:104)
	at com.structurizr.api.StructurizrClient.mergeWorkspace(StructurizrClient.java:152)
	at at.gv.justiz.ju30.architecture.Target2015.main(Target2015.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.structurizr.Workspace["model"]->com.structurizr.model.Model["softwareSystems"]->com.structurizr.model.SoftwareSystem["relationships"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)

**Comment by klu2** [comment]
it works fine with the latest version on github on the master branch, so I suppose all we need is a release here

**Comment by simonbrowndotje** [comment]
Thanks Klaus ... are you using the 0.2.1 release on Bintray/JCenter?

**Comment by klu2** [comment]
no, cause https://www.structurizr.com/getting-started/java tells me to use 0.2

**Comment by simonbrowndotje** [comment]
Ah, yes, apologies, there's a story behind that (I'll e-mail you).
